### ISSUE TITLE
Could you please provide the training data and code?

### ISSUE THREAD

**Issue by zhangjiatao** [ShuangLI59/Language-Model-Pre-training-Improves-Generalization-in-Policy-Learning#1]
The provided source code seems not give the data and code for training. Could you please release this part>

**Comment by wang-zm18** [comment]
Hello, can you run `inference.sh` normally?

**Comment by ShuangLI59** [comment]
Thanks a lot for your interest! We are building a larger and more realistic environment for decision-making tasks. We will release the new dataset soon.

**Comment by WangYong-Design** [comment]
Hi,if there is a rough schedule (monthly?) for the training data?

**Comment by wenqian-ye** [comment]
Any updates on releasing the training code and data?

**Comment by lgy0404** [comment]
Any updates on releasing the training code and data?

**Comment by yanan1116** [comment]
any updates on releasing the dataset including the goal of each sample ? @ShuangLI59
